version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./keys:/app/keys
      - ./public:/app/public
      - ./views:/app/views
      - ./licenses.db:/app/licenses.db
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - ./data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - app
    restart: unless-stopped
